---
on: [push, pull_request]
name: lint-test

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  # tests:
  #   runs-on: ubuntu-latest
  #   # timeout-minutes: 10
  #   # if: ${{ needs.config.outputs.has_tests == 'true' }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: folke/github/neovim@main
  #     # - name: Test Cache
  #     #   uses: actions/cache@v4
  #     #   with:
  #     #     path: .tests
  #     #     key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua', 'scripts/test') }}
  #     - name: Run Tests
  #       run: nvim -l tests/minit.lua --minitest
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nvim-versions: ["stable", "nightly"]
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - uses: cachix/install-nix-action@v26

      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test Cache
        uses: actions/cache@v4
        with:
          path: .tests
          key: ${{ runner.os }}-${{ matrix.nvim-versions }}-tests-${{ hashFiles('tests/minit.lua', 'devenv.nix', 'devenv.lock') }}

      - name: Run test
        run: |
          devenv test
